[project]
name = "httpx-disable-verify"
version = "0.1.1"
description = "Block httpx certificate verification using a monkey patch."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "typer>=0.20.0",
]
